title: 'Nordpool Day-ahead prices'
time_zone: 'Europe/Riga'
smtp:
  server : smtp.gmail.com
  port: 465
email:
  from: NordPoolScript
  to: your_email@test.com
  bcc:
plot:
  xlabel: 'Time'
  ylabel: 'kWh price, EUR'
  width: 16 #inches
  height: 8 #inches
  red_threshold: 0.3 #higher than 0.3 EUR/kWh
  orange_threshold: 0.2
  blue_threshold: 0.1
